development:
  adapter: postgresql
  encoding: unicode
  database: labs_pong
  pool: 5
  username: luxcerique
  password: luxcerique

test:
  adapter: postgresql
  encoding: unicode
  database: labs_pong_test
  pool: 5
  username: luxcerique
  password: luxcerique
